# TP4/configs/sage_sampling.yaml
seed: 42
device: "cuda"
epochs: 50
lr: 0.01
weight_decay: 0.01

sage:
  hidden_dim: 64
  dropout: 0.5

sampling:
  batch_size: 64
  num_neighbors_l1: 25
  num_neighbors_l2: 10
    